Repository univapay/univapay-node, pull requests merged in 2020-10, with the labels that each got.

#67 Update verification types
  src/resources/Verification.ts
Labels: Enhancement

#68 Feature/pierreh/64/add top level imports
  .circleci/config.yml
  package.json
  src/api/index.ts
  src/common/index.ts
  src/errors/index.ts
  src/index.ts
  src/resources/index.ts
  src/utils/index.ts
Labels: Technical Debt

#71 Add au pay to qr brands
  src/resources/common/enums.ts
Labels: Technical Debt

#70 Update dependencies
  package-lock.json
  package.json
Labels: Technical Debt

#73 Add missing qr gateways
  src/resources/common/enums.ts
Labels: Bug

#75 Add reuccuring token deleted webhook
  src/resources/WebHooks.ts
Labels: Enhancement

#74 fix unhandled error type in serializeErrorResponse
  src/errors/RequestResponseError.ts
Labels: Bug
