Repository univapay/univapay-node, pull requests merged in 2020-08, with the labels that each got.

#45 Fix/pierreh/update libaries
  package-lock.json
  package.json
  src/resources/Resource.ts
  src/sdk/PaymentsSDK.ts
  test/utils/routes.ts
Labels: Technical Debt

#46 add auth param in BankAccounts for consistency
  src/resources/BankAccounts.ts
Labels: Bug

#47 Re-add origami to qr gateway and brand
  src/resources/common/enums.ts
Labels: Technical Debt

#49 Add pay pay online to online gateway enum
  src/resources/common/enums.ts
Labels: Enhancement

#51 Feature/pierreh/no ticket/add online configuration
  src/resources/CheckoutInfo.ts
  src/resources/common/Configuration.ts
  src/resources/common/Platform.ts
  test/fixtures/checkout-info.ts
  test/fixtures/common/configuration.ts
  test/fixtures/platforms.ts
Labels: Enhancement

#53 remove filter logic for SendData, refactor getHeaders
  src/api/RestAPI.ts
  test/specs/api.specs.ts
Labels: Enhancement
