Repository univapay/univapay-node, pull requests merged in 2020-07, with the labels that each got.

#22 Artificially bring coverage up
  package.json
  src/index.ts
  src/resources/Resource.ts
  test/specs/common/ignoreDescriptor.specs.ts
Labels: Technical Debt

#23 Fix/pierreh/admin 412/update types
  src/resources/BankAccounts.ts
  src/resources/Cancels.ts
  src/resources/Charges.ts
  src/resources/Corporation.ts
  src/resources/Ledgers.ts
  src/resources/Refunds.ts
  src/resources/Stores.ts
  src/resources/Subscriptions.ts
  src/resources/TransactionTokens.ts
  src/resources/Transfers.ts
  src/resources/WebHooks.ts
  src/resources/common/Configuration.ts
  src/resources/common/types.ts
  test/fixtures/common/configuration.ts
Labels: Technical Debt

#24 Add trigger templating to list response
  src/resources/WebHooks.ts
Labels: Technical Debt

#25 Add tempalting for webhook on the sdk level
  src/index.ts
Labels: Technical Debt

#27 Add IssuerUrl resource
  src/resources/Charges.ts
  src/resources/TransactionTokens.ts
  test/specs/charges.specs.ts
Labels: Enhancement

#29 Fix getIssuerToken return type
  src/resources/Charges.ts
Labels: Bug

#40 Add missing error
  src/errors/APIError.ts
Labels: Enhancement

#42 Improve serialize error resilience
  src/errors/RequestResponseError.ts
Labels: Bug
