Repository univapay/univapay-node, pull requests merged in 2020-06, with the labels that each got.

#16 Feature/laxa88/noqa/api error update
  src/errors/parser.ts
  src/resources/Resource.ts
  src/utils/object.ts
Labels: bug, enhancement

#17 Fix/laxa88/noqa/transform keys
  src/utils/object.ts
Labels: bug

#20 Add line pay to qr enums
  src/resources/common/enums.ts
Labels: enhancement
