Repository univapay/univapay-node, pull requests merged in 2020-11, with the labels that each got.

#79 Fix/pierreh/update dependencies
  package-lock.json
  package.json
  test/specs/api.specs.ts
Labels: Technical Debt, dependencies

#80 Add cvv authorized to transaction token item
  src/resources/TransactionTokens.ts
Labels: Enhancement

#81 update defs for paidy data
  src/resources/TransactionTokens.ts
Labels: Enhancement

#83 Fix cvv auth type and group att interface for token data
  src/resources/TransactionTokens.ts
Labels: Enhancement

#84 add update platform config
  src/resources/common/Platform.ts
  test/fixtures/platforms.ts
Labels: Enhancement

#86 Rempve lodash
  package-lock.json
  package.json
  src/errors/RequestResponseError.ts
  test/specs/verification.specs.ts
Labels: Bug, Technical Debt

#85 Add public ecform data
  src/resources/ECForms.ts
  src/resources/index.ts
Labels: Technical Debt
