Repository univapay/univapay-node, pull requests merged in 2020-12, with the labels that each got.

#88 Fix typo
  src/resources/ECForms.ts
Labels: Technical Debt

#89 Fix/pierreh/xport ec form in sdk
  src/index.ts
  test/specs/ec-forms.specs.ts
Labels: Enhancement

#90 update ScheduledPaymentItem with new prop
  src/resources/Subscriptions.ts
Labels: Enhancement

#91 Allow overriding the key formatter
  src/api/RestAPI.ts
  src/api/utils/payload.ts
  src/resources/CRUDResource.ts
  src/resources/Resource.ts
  test/specs/payload.specs.ts
Labels: Enhancement

#92 Fix/pierreh/integrate ec form api
  src/errors/RequestResponseError.ts
  src/resources/ECForms.ts
  test/specs/ec-forms.specs.ts
Labels: Enhancement

#93 Add missing ec-form properties
  src/resources/ECForms.ts
Labels: Enhancement

#94 Check for symbol errors
  src/errors/RequestResponseError.ts
Labels: Bug

#95 Mark more properties as optional
  src/resources/ECForms.ts
Labels: Enhancement

#96 Update ECForms.ts
  src/resources/ECForms.ts
Labels: Enhancement

#97 Mark ec form custom field titles as partial
  src/resources/ECForms.ts
Labels: Enhancement

#98 Add none array errors handling
  src/errors/RequestResponseError.ts
Labels: Bug

#99 Add new refresh header
  src/api/utils/JWT.ts
Labels: Technical Debt

#100 Update user transation configuration
  src/resources/common/Configuration.ts
Labels: Enhancement

#103 Update dependencies
  .eslintrc
  package-lock.json
  package.json
Labels: Technical Debt

#102 Update ec form url
  src/resources/ECForms.ts
  test/specs/ec-forms.specs.ts
Labels: Technical Debt

#106 Fix/pierreh/update dependencies
  package-lock.json
  package.json
  src/api/RestAPI.ts
  src/api/utils/JWT.ts
  src/api/utils/payload.ts
  src/resources/Resource.ts
  src/utils/object.ts
  test/specs/object.specs.ts
  test/specs/payload.specs.ts
Labels: Technical Debt

#107 Feature/laxa88/checkout email
  src/index.ts
  src/resources/ECForms.ts
  src/resources/Emails.ts
  src/resources/index.ts
  test/specs/emails.specs.ts
Labels: Enhancement

#108 Fix/pierreh/fix nested ignored keys
  src/api/RestAPI.ts
  src/api/utils/payload.ts
  src/utils/object.ts
  test/specs/object.specs.ts
Labels: Bug

#109 Change jwt-decode to es5 compatible library
  package-lock.json
  package.json
  src/api/utils/JWT.ts
Labels: Technical Debt
