Repository univapay/univapay-node, pull requests merged in 2021-11, with the labels that each got.

#179 Fix/pierreh/update dependencies
  .c8rc.json
  .eslintignore
  .github/dependabot.yml
  README.en.md
  README.md
  package-lock.json
  package.json
Labels: Technical Debt

#183 Remove release script
  package-lock.json
  package.json
Labels: Technical Debt

#192 Fix/pierreh/fix metadata bigint
  .eslintrc
  package-lock.json
  package.json
  src/api/RestAPI.ts
  src/resources/Resource.ts
  src/utils/fetch.ts
  src/utils/object.ts
  test/specs/fetch.specs.ts
  test/specs/object.specs.ts
  test/specs/sdk.specs.ts
Labels: Bug

#186 Add ec recurring parameters
  src/resources/ECFormLinks.ts
  test/fixtures/ec-form-link.ts
Labels: Enhancement

#194 Update platform configuration
  src/resources/common/Platform.ts
  test/fixtures/platforms.ts
Labels: Bug

#202 Add customs declaration finished webhook
  src/resources/WebHooks.ts
Labels: Enhancement

#208 Add poll subscription and first charge helper
  src/api/RestAPI.ts
  src/resources/Subscriptions.ts
  test/fixtures/charge.ts
  test/fixtures/subscription.ts
  test/specs/subscriptions.specs.ts
Labels: Enhancement

#212 Ignore big decimal for form data
  src/api/utils/payload.ts
Labels: Bug

#216 Update typescript
  package-lock.json
  package.json
  tsconfig.esm.json
Labels: Technical Debt
