Repository univapay/univapay-node, pull requests merged in 2022-05, with the labels that each got.

#396 Fix/pierreh/fix big int parser for float
  package-lock.json
  package.json
  src/api/RestAPI.ts
  src/api/utils/payload.ts
  src/errors/RequestResponseError.ts
  src/utils/fetch.ts
  test/specs/fetch.specs.ts
Labels: Bug

#411 Add subscription start day of month parameter
  src/resources/ECFormLinks.ts
Labels: Enhancement

#412 Add poll iteration callback and more tests
  src/api/RestAPI.ts
  src/resources/Cancels.ts
  src/resources/Charges.ts
  src/resources/Refunds.ts
  src/resources/Subscriptions.ts
  test/specs/cancels.specs.ts
  test/specs/charges.specs.ts
  test/specs/refunds.specs.ts
  test/specs/subscriptions.specs.ts
Labels: Enhancement

#413 Fix/pierreh/refactors
  package-lock.json
  package.json
  src/api/RestAPI.ts
  src/errors/RequestResponseError.ts
  test/specs/api.specs.ts
  test/specs/cancels.specs.ts
  test/specs/charges.specs.ts
  test/specs/refunds.specs.ts
  test/specs/subscriptions.specs.ts
  test/utils/poll-helper.ts
Labels: Technical Debt

#419 Add minimumChargeAmounts
  src/resources/common/Configuration.ts
  test/fixtures/common/configuration.ts
Labels: Enhancement

#420 Downgrade package for cjs builds
  package-lock.json
  package.json
Labels: Technical Debt
