Repository univapay/univapay-node, pull requests merged in 2022-11, with the labels that each got.

#615 Fix/pierreh/fix array handling for get request
  src/api/RestAPI.ts
  test/specs/api.specs.ts
Labels: Bug

#616 Add new notification keys
  src/resources/common/Configuration.ts
Labels: Enhancement

#622 Cleanup and add missing parameters
  src/api/utils/JWT.ts
  src/resources/common/Configuration.ts
Labels: Enhancement

#628 Attempt to fix login issue and cleanup
  src/api/RestAPI.ts
  src/api/utils/JWT.ts
  src/api/utils/userAgent.ts
  src/errors/parser.ts
  test/specs/jwt.specs.ts
Labels: Bug

#629 Remove unsafe expiry check
  src/api/RestAPI.ts
  test/specs/api.specs.ts
Labels: Bug

#630 Add expiry time shift to token params
  src/resources/TransactionTokens.ts
Labels: Technical Debt

#636 Make system manager parameters optional
  src/resources/Verification.ts
Labels: Enhancement

#642 Add expiration period to tokens
  src/resources/TransactionTokens.ts
  src/resources/common/Configuration.ts
Labels: Enhancement

#643 Add subscription capture parameters
  src/resources/Subscriptions.ts
Labels: Technical Debt
